medic_api:
    resource: "@MedicAPIBundle/Controller/"
    type:     annotation
    prefix:   /

medic_dashboard:
    resource: "@MedicDashboardBundle/Controller/"
    type:     annotation
    prefix:   /
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

